# refer to https://docs.streamlit.io/library/advanced-features/configuration#set-configuration-options
[logger]
messageFormat = "%(asctime)s %(message)s"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 2

[browser]
# Internet address where users should point their browsers in order to
# connect to the app. Can be IP address or DNS name and path.
# This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser
# Default: "localhost"
serverAddress = "localhost"